export { httpClient } from './httpClient'
export { parseApiError } from './error'
export type { ApiError } from './error'
export { roomsApi } from './endpoints/rooms'
export type { Room } from './endpoints/rooms'
export { messagesApi } from './endpoints/messages'
export type { Message } from './endpoints/messages'
export { membersApi } from './endpoints/members'
export type { Member } from './endpoints/members'
export { searchApi } from './endpoints/search'
export type { SearchResult } from './endpoints/search'
